# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NcoreCli < Formula
  desc "Search and download torrents from ncore.pro"
  homepage "https://github.com/zsolthajnal/ncore-cli"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zsolthajnal/ncore-cli/releases/download/v2.0.1/ncore-cli_darwin_amd64.tar.gz"
      sha256 "957e7e9220aa1e9fa157b087801519f1442b18d9773d2e73c45e4317fcd6ba13"

      define_method(:install) do
        bin.install "ncore-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zsolthajnal/ncore-cli/releases/download/v2.0.1/ncore-cli_darwin_arm64.tar.gz"
      sha256 "b18ed7eab2a69974f5af37c5087d847188b28e9c1ee99e8e0d83ff915482254a"

      define_method(:install) do
        bin.install "ncore-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsolthajnal/ncore-cli/releases/download/v2.0.1/ncore-cli_linux_amd64.tar.gz"
      sha256 "6e21ad06cf2f25c8f9abd0c59e9dac47e9db51c30442594d76004b48173f9d72"
      define_method(:install) do
        bin.install "ncore-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsolthajnal/ncore-cli/releases/download/v2.0.1/ncore-cli_linux_arm64.tar.gz"
      sha256 "6b68d67a7b710dd0bbf2065eb488e1809c2c6d744a970572ed999a20a8488e9f"
      define_method(:install) do
        bin.install "ncore-cli"
      end
    end
  end

  test do
    system "#{bin}/ncore-cli", "help"
  end
end
