# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NcoreCli < Formula
  desc "Search and download torrents from ncore.pro"
  homepage "https://github.com/zsolthajnal/ncore-cli"
  version "2.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zsolthajnal/ncore-cli/releases/download/v2.0.3/ncore-cli_darwin_amd64.tar.gz"
      sha256 "e9191d839f48623e735260702f99543aa9facbc75f959c411dab3f9d69b173ef"

      define_method(:install) do
        bin.install "ncore-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zsolthajnal/ncore-cli/releases/download/v2.0.3/ncore-cli_darwin_arm64.tar.gz"
      sha256 "87eec3625ca27b51c12092e0e74e50d0bcd48481b8d0c76bc4ff72be46f53e8d"

      define_method(:install) do
        bin.install "ncore-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsolthajnal/ncore-cli/releases/download/v2.0.3/ncore-cli_linux_amd64.tar.gz"
      sha256 "2a1c3c832e700a1b2b43fd9a74eef0128b735c40b4f69d9d44d5867a42e4a865"
      define_method(:install) do
        bin.install "ncore-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsolthajnal/ncore-cli/releases/download/v2.0.3/ncore-cli_linux_arm64.tar.gz"
      sha256 "50b90432d4839f49fc414d65849842379b0580a26a9dceafd866cadf31b8d04d"
      define_method(:install) do
        bin.install "ncore-cli"
      end
    end
  end

  test do
    system "#{bin}/ncore-cli", "help"
  end
end
